[build]
  publish = "."

[[redirects]]
  from   = "http://imgcompro.com/*"
  to     = "https://imgcompro.com/:splat"
  status = 301
  force  = true

[[redirects]]
  from   = "https://www.imgcompro.com/*"
  to     = "https://imgcompro.com/:splat"
  status = 301
  force  = true

[[redirects]]
  from   = "/privacy"
  to     = "/privacy.html"
  status = 200

[[redirects]]
  from   = "/*"
  to     = "/index.html"
  status = 200
